### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by yaskermezli** [github/multimap#2]
Hi, I'm trying to install the multimap tool using this command: " npm install @github/multimap"

But I have this errors:

`npm ERR! Linux 5.4.0-77-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "@github/multimap"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:190:5
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kermezly/npm-debug.log
`

any help, please?

Thank you.

**Comment by dgreif** [comment]
It looks like you have an extremely old version of `npm`.  Could you tryin installing a newer version of `node` (which includes a newer version of `npm`?  If you want to keep the older version of node, you can also just update npm by running `npm i -g npm@6`
